/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as MemberRouteImport } from './routes/member'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MemberSubscriptionsRouteImport } from './routes/member.subscriptions'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberAttendanceRouteImport } from './routes/member.attendance'
import { Route as AdminTrainersRouteImport } from './routes/admin.trainers'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSportsRouteImport } from './routes/admin.sports'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'

const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MemberSubscriptionsRoute = MemberSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberAttendanceRoute = MemberAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => MemberRoute,
} as any)
const AdminTrainersRoute = AdminTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSportsRoute = AdminSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/packages': typeof PackagesRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/sports': typeof SportsRoute
  '/trainers': typeof TrainersRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/member/attendance': typeof MemberAttendanceRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/subscriptions': typeof MemberSubscriptionsRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/sports': typeof SportsRoute
  '/trainers': typeof TrainersRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/member/attendance': typeof MemberAttendanceRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/subscriptions': typeof MemberSubscriptionsRoute
  '/admin': typeof AdminIndexRoute
  '/member': typeof MemberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/packages': typeof PackagesRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/sports': typeof SportsRoute
  '/trainers': typeof TrainersRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/member/attendance': typeof MemberAttendanceRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/subscriptions': typeof MemberSubscriptionsRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/member'
    | '/packages'
    | '/plans'
    | '/register'
    | '/sports'
    | '/trainers'
    | '/admin/attendance'
    | '/admin/members'
    | '/admin/packages'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/sports'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/admin/trainers'
    | '/member/attendance'
    | '/member/profile'
    | '/member/subscriptions'
    | '/admin/'
    | '/member/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/packages'
    | '/plans'
    | '/register'
    | '/sports'
    | '/trainers'
    | '/admin/attendance'
    | '/admin/members'
    | '/admin/packages'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/sports'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/admin/trainers'
    | '/member/attendance'
    | '/member/profile'
    | '/member/subscriptions'
    | '/admin'
    | '/member'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/member'
    | '/packages'
    | '/plans'
    | '/register'
    | '/sports'
    | '/trainers'
    | '/admin/attendance'
    | '/admin/members'
    | '/admin/packages'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/sports'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/admin/trainers'
    | '/member/attendance'
    | '/member/profile'
    | '/member/subscriptions'
    | '/admin/'
    | '/member/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRouteWithChildren
  PackagesRoute: typeof PackagesRoute
  PlansRoute: typeof PlansRoute
  RegisterRoute: typeof RegisterRoute
  SportsRoute: typeof SportsRoute
  TrainersRoute: typeof TrainersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/member/subscriptions': {
      id: '/member/subscriptions'
      path: '/subscriptions'
      fullPath: '/member/subscriptions'
      preLoaderRoute: typeof MemberSubscriptionsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/attendance': {
      id: '/member/attendance'
      path: '/attendance'
      fullPath: '/member/attendance'
      preLoaderRoute: typeof MemberAttendanceRouteImport
      parentRoute: typeof MemberRoute
    }
    '/admin/trainers': {
      id: '/admin/trainers'
      path: '/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AdminTrainersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sports': {
      id: '/admin/sports'
      path: '/sports'
      fullPath: '/admin/sports'
      preLoaderRoute: typeof AdminSportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSportsRoute: typeof AdminSportsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTrainersRoute: typeof AdminTrainersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSportsRoute: AdminSportsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTrainersRoute: AdminTrainersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MemberRouteChildren {
  MemberAttendanceRoute: typeof MemberAttendanceRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberSubscriptionsRoute: typeof MemberSubscriptionsRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberAttendanceRoute: MemberAttendanceRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberSubscriptionsRoute: MemberSubscriptionsRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRouteWithChildren,
  PackagesRoute: PackagesRoute,
  PlansRoute: PlansRoute,
  RegisterRoute: RegisterRoute,
  SportsRoute: SportsRoute,
  TrainersRoute: TrainersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
